//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA.Web.ContratoServic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroContratosReq", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroContratosReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCeseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaIniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoContField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombTrabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroDniTrabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCese {
            get {
                return this.FechaCeseField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCeseField, value) != true)) {
                    this.FechaCeseField = value;
                    this.RaisePropertyChanged("FechaCese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinField, value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaIni {
            get {
                return this.fechaIniField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaIniField, value) != true)) {
                    this.fechaIniField = value;
                    this.RaisePropertyChanged("fechaIni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoCont {
            get {
                return this.idTipoContField;
            }
            set {
                if ((this.idTipoContField.Equals(value) != true)) {
                    this.idTipoContField = value;
                    this.RaisePropertyChanged("idTipoCont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombTrab {
            get {
                return this.nombTrabField;
            }
            set {
                if ((object.ReferenceEquals(this.nombTrabField, value) != true)) {
                    this.nombTrabField = value;
                    this.RaisePropertyChanged("nombTrab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroContrato {
            get {
                return this.nroContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.nroContratoField, value) != true)) {
                    this.nroContratoField = value;
                    this.RaisePropertyChanged("nroContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroDniTrab {
            get {
                return this.nroDniTrabField;
            }
            set {
                if ((object.ReferenceEquals(this.nroDniTrabField, value) != true)) {
                    this.nroDniTrabField = value;
                    this.RaisePropertyChanged("nroDniTrab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroContratosResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroContratosResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.ContratoServic.Contrato_E> lstContratos_EField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.ContratoServic.Contrato_E> lstContratos_E {
            get {
                return this.lstContratos_EField;
            }
            set {
                if ((object.ReferenceEquals(this.lstContratos_EField, value) != true)) {
                    this.lstContratos_EField = value;
                    this.RaisePropertyChanged("lstContratos_E");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E")]
    [System.SerializableAttribute()]
    public partial class Contrato_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCeseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombUsuarioModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombUsuarioRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoContratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCese {
            get {
                return this.FechaCeseField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCeseField, value) != true)) {
                    this.FechaCeseField = value;
                    this.RaisePropertyChanged("FechaCese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFinContrato {
            get {
                return this.FechaFinContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinContratoField, value) != true)) {
                    this.FechaFinContratoField = value;
                    this.RaisePropertyChanged("FechaFinContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicioContrato {
            get {
                return this.FechaInicioContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioContratoField, value) != true)) {
                    this.FechaInicioContratoField = value;
                    this.RaisePropertyChanged("FechaInicioContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaModificacionField, value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaRegistroField, value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("Fecharegistró");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrato {
            get {
                return this.IdContratoField;
            }
            set {
                if ((this.IdContratoField.Equals(value) != true)) {
                    this.IdContratoField = value;
                    this.RaisePropertyChanged("IdContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoContrato {
            get {
                return this.IdTipoContratoField;
            }
            set {
                if ((this.IdTipoContratoField.Equals(value) != true)) {
                    this.IdTipoContratoField = value;
                    this.RaisePropertyChanged("IdTipoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTrabajador {
            get {
                return this.IdTrabajadorField;
            }
            set {
                if ((this.IdTrabajadorField.Equals(value) != true)) {
                    this.IdTrabajadorField = value;
                    this.RaisePropertyChanged("IdTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IDUSUARIOregistró");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoContrato {
            get {
                return this.MontoContratoField;
            }
            set {
                if ((this.MontoContratoField.Equals(value) != true)) {
                    this.MontoContratoField = value;
                    this.RaisePropertyChanged("MontoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroContrato {
            get {
                return this.NroContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroContratoField, value) != true)) {
                    this.NroContratoField = value;
                    this.RaisePropertyChanged("NroContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombTrabajador {
            get {
                return this.nombTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombTrabajadorField, value) != true)) {
                    this.nombTrabajadorField = value;
                    this.RaisePropertyChanged("nombTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombUsuarioMod {
            get {
                return this.nombUsuarioModField;
            }
            set {
                if ((object.ReferenceEquals(this.nombUsuarioModField, value) != true)) {
                    this.nombUsuarioModField = value;
                    this.RaisePropertyChanged("nombUsuarioMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombUsuarioReg {
            get {
                return this.nombUsuarioRegField;
            }
            set {
                if ((object.ReferenceEquals(this.nombUsuarioRegField, value) != true)) {
                    this.nombUsuarioRegField = value;
                    this.RaisePropertyChanged("nombUsuarioReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nroDocumentoField, value) != true)) {
                    this.nroDocumentoField = value;
                    this.RaisePropertyChanged("nroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoContratoField, value) != true)) {
                    this.tipoContratoField = value;
                    this.RaisePropertyChanged("tipoContrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContratoServic.IContratoServ")]
    public interface IContratoServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServ/listarxfiltro", ReplyAction="http://tempuri.org/IContratoServ/listarxfiltroResponse")]
        CAPA.Web.ContratoServic._listarxfiltroContratosResp listarxfiltro(CAPA.Web.ContratoServic._listarxfiltroContratosReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServ/listarxfiltro", ReplyAction="http://tempuri.org/IContratoServ/listarxfiltroResponse")]
        System.Threading.Tasks.Task<CAPA.Web.ContratoServic._listarxfiltroContratosResp> listarxfiltroAsync(CAPA.Web.ContratoServic._listarxfiltroContratosReq objRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContratoServChannel : CAPA.Web.ContratoServic.IContratoServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContratoServClient : System.ServiceModel.ClientBase<CAPA.Web.ContratoServic.IContratoServ>, CAPA.Web.ContratoServic.IContratoServ {
        
        public ContratoServClient() {
        }
        
        public ContratoServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContratoServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPA.Web.ContratoServic._listarxfiltroContratosResp listarxfiltro(CAPA.Web.ContratoServic._listarxfiltroContratosReq objRequest) {
            return base.Channel.listarxfiltro(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.ContratoServic._listarxfiltroContratosResp> listarxfiltroAsync(CAPA.Web.ContratoServic._listarxfiltroContratosReq objRequest) {
            return base.Channel.listarxfiltroAsync(objRequest);
        }
    }
}
