//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA.Web.UbigeoServic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroUbigeoReq", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroUbigeoReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoUbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoUbigeo {
            get {
                return this.codigoUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoUbigeoField, value) != true)) {
                    this.codigoUbigeoField = value;
                    this.RaisePropertyChanged("codigoUbigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroDepartamentoResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroDepartamentoResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsDepartamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsDepartamento {
            get {
                return this.lsDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.lsDepartamentoField, value) != true)) {
                    this.lsDepartamentoField = value;
                    this.RaisePropertyChanged("lsDepartamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubigeo_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E")]
    [System.SerializableAttribute()]
    public partial class Ubigeo_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoUbigeo {
            get {
                return this.codigoUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoUbigeoField, value) != true)) {
                    this.codigoUbigeoField = value;
                    this.RaisePropertyChanged("codigoUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Ubigeo {
            get {
                return this.id_UbigeoField;
            }
            set {
                if ((this.id_UbigeoField.Equals(value) != true)) {
                    this.id_UbigeoField = value;
                    this.RaisePropertyChanged("id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroProvinciaResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroProvinciaResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsProvincia {
            get {
                return this.lsProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.lsProvinciaField, value) != true)) {
                    this.lsProvinciaField = value;
                    this.RaisePropertyChanged("lsProvincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroDistritoResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroDistritoResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.UbigeoServic.Ubigeo_E> lsDistrito {
            get {
                return this.lsDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.lsDistritoField, value) != true)) {
                    this.lsDistritoField = value;
                    this.RaisePropertyChanged("lsDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UbigeoServic.IUbigeoServ")]
    public interface IUbigeoServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarDepartamento", ReplyAction="http://tempuri.org/IUbigeoServ/listarDepartamentoResponse")]
        CAPA.Web.UbigeoServic._listarxfiltroDepartamentoResp listarDepartamento(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarDepartamento", ReplyAction="http://tempuri.org/IUbigeoServ/listarDepartamentoResponse")]
        System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroDepartamentoResp> listarDepartamentoAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarProvincia", ReplyAction="http://tempuri.org/IUbigeoServ/listarProvinciaResponse")]
        CAPA.Web.UbigeoServic._listarxfiltroProvinciaResp listarProvincia(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarProvincia", ReplyAction="http://tempuri.org/IUbigeoServ/listarProvinciaResponse")]
        System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroProvinciaResp> listarProvinciaAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarDistrito", ReplyAction="http://tempuri.org/IUbigeoServ/listarDistritoResponse")]
        CAPA.Web.UbigeoServic._listarxfiltroDistritoResp listarDistrito(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServ/listarDistrito", ReplyAction="http://tempuri.org/IUbigeoServ/listarDistritoResponse")]
        System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroDistritoResp> listarDistritoAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUbigeoServChannel : CAPA.Web.UbigeoServic.IUbigeoServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UbigeoServClient : System.ServiceModel.ClientBase<CAPA.Web.UbigeoServic.IUbigeoServ>, CAPA.Web.UbigeoServic.IUbigeoServ {
        
        public UbigeoServClient() {
        }
        
        public UbigeoServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UbigeoServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbigeoServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbigeoServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPA.Web.UbigeoServic._listarxfiltroDepartamentoResp listarDepartamento(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarDepartamento(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroDepartamentoResp> listarDepartamentoAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarDepartamentoAsync(objRequest);
        }
        
        public CAPA.Web.UbigeoServic._listarxfiltroProvinciaResp listarProvincia(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarProvincia(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroProvinciaResp> listarProvinciaAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarProvinciaAsync(objRequest);
        }
        
        public CAPA.Web.UbigeoServic._listarxfiltroDistritoResp listarDistrito(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarDistrito(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.UbigeoServic._listarxfiltroDistritoResp> listarDistritoAsync(CAPA.Web.UbigeoServic._listarxfiltroUbigeoReq objRequest) {
            return base.Channel.listarDistritoAsync(objRequest);
        }
    }
}
