//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA.Web.OAUsuarioServic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroUsuarioOAReq", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroUsuarioOAReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoSolicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nroRucOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rowsPageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoSolic {
            get {
                return this.idTipoSolicField;
            }
            set {
                if ((this.idTipoSolicField.Equals(value) != true)) {
                    this.idTipoSolicField = value;
                    this.RaisePropertyChanged("idTipoSolic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nroRucOA {
            get {
                return this.nroRucOAField;
            }
            set {
                if ((this.nroRucOAField.Equals(value) != true)) {
                    this.nroRucOAField = value;
                    this.RaisePropertyChanged("nroRucOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumb {
            get {
                return this.pageNumbField;
            }
            set {
                if ((this.pageNumbField.Equals(value) != true)) {
                    this.pageNumbField = value;
                    this.RaisePropertyChanged("pageNumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razSocial {
            get {
                return this.razSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razSocialField, value) != true)) {
                    this.razSocialField = value;
                    this.RaisePropertyChanged("razSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rowsPage {
            get {
                return this.rowsPageField;
            }
            set {
                if ((this.rowsPageField.Equals(value) != true)) {
                    this.rowsPageField = value;
                    this.RaisePropertyChanged("rowsPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroUsuarioOAResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroUsuarioOAResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.OAUsuarioServic.OAUsuario_E> lstUsuarioOAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.OAUsuarioServic.OAUsuario_E> lstUsuarioOA {
            get {
                return this.lstUsuarioOAField;
            }
            set {
                if ((object.ReferenceEquals(this.lstUsuarioOAField, value) != true)) {
                    this.lstUsuarioOAField = value;
                    this.RaisePropertyChanged("lstUsuarioOA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAUsuario_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.SEL_E")]
    [System.SerializableAttribute()]
    public partial class OAUsuario_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailRepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NDniRepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoSolicitanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailRepresentanteLegal {
            get {
                return this.EmailRepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailRepresentanteLegalField, value) != true)) {
                    this.EmailRepresentanteLegalField = value;
                    this.RaisePropertyChanged("EmailRepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaRegistroField, value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("Fecharegistró");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoSolicitante {
            get {
                return this.IdTipoSolicitanteField;
            }
            set {
                if ((this.IdTipoSolicitanteField.Equals(value) != true)) {
                    this.IdTipoSolicitanteField = value;
                    this.RaisePropertyChanged("IdTipoSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioOA {
            get {
                return this.IdUsuarioOAField;
            }
            set {
                if ((this.IdUsuarioOAField.Equals(value) != true)) {
                    this.IdUsuarioOAField = value;
                    this.RaisePropertyChanged("IdUsuarioOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NDniRepresentanteLegal {
            get {
                return this.NDniRepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.NDniRepresentanteLegalField, value) != true)) {
                    this.NDniRepresentanteLegalField = value;
                    this.RaisePropertyChanged("NDniRepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepresentanteLegal {
            get {
                return this.RepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentanteLegalField, value) != true)) {
                    this.RepresentanteLegalField = value;
                    this.RaisePropertyChanged("RepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucOA {
            get {
                return this.RucOAField;
            }
            set {
                if ((object.ReferenceEquals(this.RucOAField, value) != true)) {
                    this.RucOAField = value;
                    this.RaisePropertyChanged("RucOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoSolicitante {
            get {
                return this.tipoSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoSolicitanteField, value) != true)) {
                    this.tipoSolicitanteField = value;
                    this.RaisePropertyChanged("tipoSolicitante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OAUsuarioServic.IUsuarioOAServ")]
    public interface IUsuarioOAServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioOAServ/listarxfiltro", ReplyAction="http://tempuri.org/IUsuarioOAServ/listarxfiltroResponse")]
        CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAResp listarxfiltro(CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioOAServ/listarxfiltro", ReplyAction="http://tempuri.org/IUsuarioOAServ/listarxfiltroResponse")]
        System.Threading.Tasks.Task<CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAResp> listarxfiltroAsync(CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAReq objRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioOAServChannel : CAPA.Web.OAUsuarioServic.IUsuarioOAServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioOAServClient : System.ServiceModel.ClientBase<CAPA.Web.OAUsuarioServic.IUsuarioOAServ>, CAPA.Web.OAUsuarioServic.IUsuarioOAServ {
        
        public UsuarioOAServClient() {
        }
        
        public UsuarioOAServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioOAServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioOAServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioOAServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAResp listarxfiltro(CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAReq objRequest) {
            return base.Channel.listarxfiltro(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAResp> listarxfiltroAsync(CAPA.Web.OAUsuarioServic._listarxfiltroUsuarioOAReq objRequest) {
            return base.Channel.listarxfiltroAsync(objRequest);
        }
    }
}
