//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA.Web.CargoTrabajadorServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroCargoTrabajadorReq", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroCargoTrabajadorReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTrabajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTrabaj {
            get {
                return this.idTrabajField;
            }
            set {
                if ((this.idTrabajField.Equals(value) != true)) {
                    this.idTrabajField = value;
                    this.RaisePropertyChanged("idTrabaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_listarxfiltroCargoTrabajadorResp", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E.filtros")]
    [System.SerializableAttribute()]
    public partial class _listarxfiltroCargoTrabajadorResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CAPA.Web.CargoTrabajadorServ.TrabajadorCargo_E> lstTrabajadorCargo_EField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CAPA.Web.CargoTrabajadorServ.TrabajadorCargo_E> lstTrabajadorCargo_E {
            get {
                return this.lstTrabajadorCargo_EField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTrabajadorCargo_EField, value) != true)) {
                    this.lstTrabajadorCargo_EField = value;
                    this.RaisePropertyChanged("lstTrabajadorCargo_E");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrabajadorCargo_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.RRHH_E")]
    [System.SerializableAttribute()]
    public partial class TrabajadorCargo_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_CeseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTrabajadorCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombUsuarioModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombUsuarioRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaModificacionField, value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaRegistroField, value) != true)) {
                    this.fechaRegistroField = value;
                    this.RaisePropertyChanged("Fecharegistró");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Cese {
            get {
                return this.Fecha_CeseField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_CeseField, value) != true)) {
                    this.Fecha_CeseField = value;
                    this.RaisePropertyChanged("Fecha_Cese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Fin {
            get {
                return this.Fecha_FinField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_FinField, value) != true)) {
                    this.Fecha_FinField = value;
                    this.RaisePropertyChanged("Fecha_Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Inicio {
            get {
                return this.Fecha_InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_InicioField, value) != true)) {
                    this.Fecha_InicioField = value;
                    this.RaisePropertyChanged("Fecha_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea {
            get {
                return this.IdAreaField;
            }
            set {
                if ((this.IdAreaField.Equals(value) != true)) {
                    this.IdAreaField = value;
                    this.RaisePropertyChanged("IdArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargo {
            get {
                return this.IdCargoField;
            }
            set {
                if ((this.IdCargoField.Equals(value) != true)) {
                    this.IdCargoField = value;
                    this.RaisePropertyChanged("IdCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJefe {
            get {
                return this.IdJefeField;
            }
            set {
                if ((this.IdJefeField.Equals(value) != true)) {
                    this.IdJefeField = value;
                    this.RaisePropertyChanged("IdJefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSede {
            get {
                return this.IdSedeField;
            }
            set {
                if ((this.IdSedeField.Equals(value) != true)) {
                    this.IdSedeField = value;
                    this.RaisePropertyChanged("IdSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTrabajador {
            get {
                return this.IdTrabajadorField;
            }
            set {
                if ((this.IdTrabajadorField.Equals(value) != true)) {
                    this.IdTrabajadorField = value;
                    this.RaisePropertyChanged("IdTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTrabajadorCargo {
            get {
                return this.IdTrabajadorCargoField;
            }
            set {
                if ((this.IdTrabajadorCargoField.Equals(value) != true)) {
                    this.IdTrabajadorCargoField = value;
                    this.RaisePropertyChanged("IdTrabajadorCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUnidad {
            get {
                return this.IdUnidadField;
            }
            set {
                if ((this.IdUnidadField.Equals(value) != true)) {
                    this.IdUnidadField = value;
                    this.RaisePropertyChanged("IdUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IDUSUARIOregistró");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string area {
            get {
                return this.areaField;
            }
            set {
                if ((object.ReferenceEquals(this.areaField, value) != true)) {
                    this.areaField = value;
                    this.RaisePropertyChanged("area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                if ((object.ReferenceEquals(this.cargoField, value) != true)) {
                    this.cargoField = value;
                    this.RaisePropertyChanged("cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jefe {
            get {
                return this.jefeField;
            }
            set {
                if ((object.ReferenceEquals(this.jefeField, value) != true)) {
                    this.jefeField = value;
                    this.RaisePropertyChanged("jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombUsuarioMod {
            get {
                return this.nombUsuarioModField;
            }
            set {
                if ((object.ReferenceEquals(this.nombUsuarioModField, value) != true)) {
                    this.nombUsuarioModField = value;
                    this.RaisePropertyChanged("nombUsuarioMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombUsuarioReg {
            get {
                return this.nombUsuarioRegField;
            }
            set {
                if ((object.ReferenceEquals(this.nombUsuarioRegField, value) != true)) {
                    this.nombUsuarioRegField = value;
                    this.RaisePropertyChanged("nombUsuarioReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sede {
            get {
                return this.sedeField;
            }
            set {
                if ((object.ReferenceEquals(this.sedeField, value) != true)) {
                    this.sedeField = value;
                    this.RaisePropertyChanged("sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trabajador {
            get {
                return this.trabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.trabajadorField, value) != true)) {
                    this.trabajadorField = value;
                    this.RaisePropertyChanged("trabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadField, value) != true)) {
                    this.unidadField = value;
                    this.RaisePropertyChanged("unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CargoTrabajadorServ.ICargoTrabajador")]
    public interface ICargoTrabajador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargoTrabajador/listarxfiltro", ReplyAction="http://tempuri.org/ICargoTrabajador/listarxfiltroResponse")]
        CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorResp listarxfiltro(CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorReq objRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargoTrabajador/listarxfiltro", ReplyAction="http://tempuri.org/ICargoTrabajador/listarxfiltroResponse")]
        System.Threading.Tasks.Task<CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorResp> listarxfiltroAsync(CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorReq objRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargoTrabajadorChannel : CAPA.Web.CargoTrabajadorServ.ICargoTrabajador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargoTrabajadorClient : System.ServiceModel.ClientBase<CAPA.Web.CargoTrabajadorServ.ICargoTrabajador>, CAPA.Web.CargoTrabajadorServ.ICargoTrabajador {
        
        public CargoTrabajadorClient() {
        }
        
        public CargoTrabajadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargoTrabajadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoTrabajadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoTrabajadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorResp listarxfiltro(CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorReq objRequest) {
            return base.Channel.listarxfiltro(objRequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorResp> listarxfiltroAsync(CAPA.Web.CargoTrabajadorServ._listarxfiltroCargoTrabajadorReq objRequest) {
            return base.Channel.listarxfiltroAsync(objRequest);
        }
    }
}
