//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA.Web.ConsultaReniecServic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_filtrarReniecReq_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.PIDE_E")]
    [System.SerializableAttribute()]
    public partial class _filtrarReniecReq_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroDniConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroDniUsuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroRucEntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pwdUsuaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroDniCon {
            get {
                return this.nroDniConField;
            }
            set {
                if ((object.ReferenceEquals(this.nroDniConField, value) != true)) {
                    this.nroDniConField = value;
                    this.RaisePropertyChanged("nroDniCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroDniUsua {
            get {
                return this.nroDniUsuaField;
            }
            set {
                if ((object.ReferenceEquals(this.nroDniUsuaField, value) != true)) {
                    this.nroDniUsuaField = value;
                    this.RaisePropertyChanged("nroDniUsua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroRucEnt {
            get {
                return this.nroRucEntField;
            }
            set {
                if ((object.ReferenceEquals(this.nroRucEntField, value) != true)) {
                    this.nroRucEntField = value;
                    this.RaisePropertyChanged("nroRucEnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwdUsua {
            get {
                return this.pwdUsuaField;
            }
            set {
                if ((object.ReferenceEquals(this.pwdUsuaField, value) != true)) {
                    this.pwdUsuaField = value;
                    this.RaisePropertyChanged("pwdUsua");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_filtrarReniecResp_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.PIDE_E")]
    [System.SerializableAttribute()]
    public partial class _filtrarReniecResp_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CAPA.Web.ConsultaReniecServic.datosReniec_E datosReniecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CAPA.Web.ConsultaReniecServic.datosReniec_E datosReniec {
            get {
                return this.datosReniecField;
            }
            set {
                if ((object.ReferenceEquals(this.datosReniecField, value) != true)) {
                    this.datosReniecField = value;
                    this.RaisePropertyChanged("datosReniec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="datosReniec_E", Namespace="http://schemas.datacontract.org/2004/07/SEL_Entidades.PIDE_E")]
    [System.SerializableAttribute()]
    public partial class datosReniec_E : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apPrimerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apSegundoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restriccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apPrimer {
            get {
                return this.apPrimerField;
            }
            set {
                if ((object.ReferenceEquals(this.apPrimerField, value) != true)) {
                    this.apPrimerField = value;
                    this.RaisePropertyChanged("apPrimer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apSegundo {
            get {
                return this.apSegundoField;
            }
            set {
                if ((object.ReferenceEquals(this.apSegundoField, value) != true)) {
                    this.apSegundoField = value;
                    this.RaisePropertyChanged("apSegundo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coResultado {
            get {
                return this.coResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.coResultadoField, value) != true)) {
                    this.coResultadoField = value;
                    this.RaisePropertyChanged("coResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deResultado {
            get {
                return this.deResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.deResultadoField, value) != true)) {
                    this.deResultadoField = value;
                    this.RaisePropertyChanged("deResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoCivilField, value) != true)) {
                    this.estadoCivilField = value;
                    this.RaisePropertyChanged("estadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenombres {
            get {
                return this.prenombresField;
            }
            set {
                if ((object.ReferenceEquals(this.prenombresField, value) != true)) {
                    this.prenombresField = value;
                    this.RaisePropertyChanged("prenombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string restriccion {
            get {
                return this.restriccionField;
            }
            set {
                if ((object.ReferenceEquals(this.restriccionField, value) != true)) {
                    this.restriccionField = value;
                    this.RaisePropertyChanged("restriccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoField, value) != true)) {
                    this.ubigeoField = value;
                    this.RaisePropertyChanged("ubigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaReniecServic.IReniecPideServ")]
    public interface IReniecPideServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecPideServ/consultaReniecPide", ReplyAction="http://tempuri.org/IReniecPideServ/consultaReniecPideResponse")]
        CAPA.Web.ConsultaReniecServic._filtrarReniecResp_E consultaReniecPide(CAPA.Web.ConsultaReniecServic._filtrarReniecReq_E objrequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReniecPideServ/consultaReniecPide", ReplyAction="http://tempuri.org/IReniecPideServ/consultaReniecPideResponse")]
        System.Threading.Tasks.Task<CAPA.Web.ConsultaReniecServic._filtrarReniecResp_E> consultaReniecPideAsync(CAPA.Web.ConsultaReniecServic._filtrarReniecReq_E objrequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReniecPideServChannel : CAPA.Web.ConsultaReniecServic.IReniecPideServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReniecPideServClient : System.ServiceModel.ClientBase<CAPA.Web.ConsultaReniecServic.IReniecPideServ>, CAPA.Web.ConsultaReniecServic.IReniecPideServ {
        
        public ReniecPideServClient() {
        }
        
        public ReniecPideServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReniecPideServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecPideServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecPideServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAPA.Web.ConsultaReniecServic._filtrarReniecResp_E consultaReniecPide(CAPA.Web.ConsultaReniecServic._filtrarReniecReq_E objrequest) {
            return base.Channel.consultaReniecPide(objrequest);
        }
        
        public System.Threading.Tasks.Task<CAPA.Web.ConsultaReniecServic._filtrarReniecResp_E> consultaReniecPideAsync(CAPA.Web.ConsultaReniecServic._filtrarReniecReq_E objrequest) {
            return base.Channel.consultaReniecPideAsync(objrequest);
        }
    }
}
